loader_version=0.19.3
additional_versions=1.21.10

# Fabric API
fabric_version=0.134.1+1.21.9

neoforge_version=21.9.16-beta

modmenu_version=16.0.1
cloth_version=20.0.149
meza_core_version=1.2.2
posthog_version=1.2.0
