loader_version=0.19.2
minecraft_version=26.1.2
additional_versions=26.1, 26.1.1

# Fabric API
fabric_version=0.147.0+26.1.2
neoforge_version=26.1.2.43-beta

modmenu_version=18.0.0-alpha.8
cloth_version=26.1.154
meza_core_version=2.0.2
posthog_version=1.2.0
