modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GPL-3.0"

[[mods]]
modId = "soundsbegone"
version = "${version}"
displayName = "SoundsBeGone"
authors = "Meza"
description = '''
Allows you to permanently disable specific sounds you don't like. Perfect for people with Misophonia!
'''
logoFile = "assets/soundsbegone/icon.png"

[[dependencies.soundsbegone]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.42-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.soundsbegone]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "soundsbegone.client.mixins.json"
