name: Crowdin Upload

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - beta
      - main
    paths:
      - "src/main/resources/assets/inventorysorter/lang/en_us.json"

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Crowdin push
        uses: crowdin/github-action@52aa776766211d83d975df51f3b9c53c2f8ba35f # v2.16.3
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
