name: Crowdin Download

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write

on:
  push:
  schedule:
    - cron: '0 */12 * * *' # Every 12 hours
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  crowdin:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        lc:
          - lc: de
            name: German
          - lc: zh-CN
            name: Chinese
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n/${{matrix.lc.lc}}

          create_pull_request: true
          commit_message: 'fix(l10n): New ${{matrix.lc.name}} translations'
          pull_request_title: 'fix(l10n): New ${{matrix.lc.name}} translations'
          pull_request_base_branch_name: 'dev'
          download_language: ${{matrix.lc.lc}}


          pull_request_labels: 'l10n, translation, ${{matrix.lc.name}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
