name: Crowdin Download

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - dev
    paths:
      - "src/main/resources/assets/inventorysorter/lang/en_us.json"
  schedule:
    - cron: '0 */12 * * *' # Every 12 hours
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 'dev'

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n

          create_pull_request: true
          skip_untranslated_strings: true
          commit_message: 'fix(l10n): additional translations'
          pull_request_title: 'fix(l10n): additional translations'
          pull_request_base_branch_name: 'dev'

          pull_request_labels: 'l10n, translation'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
